/*
* Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
* kraio is licensed under the Mulan PSL v2.
* You can use this software according to the terms and conditions of the Mulan PSL v2.
* You may obtain a copy of Mulan PSL v2 at:
*     http://license.coscl.org.cn/MulanPSL2
* THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
* PURPOSE.
* See the Mulan PSL v2 for more details.
*
* configuration file
*/

# The default size of each fd is 256 KB.
fd_entry_buffer_size = 262144

# Interface offload. Default value：
# api=["write", "writev", "send", "sendto", "sendmsg"]
write = "true"

# Whether to enable send callback for asynchronously processing the return values of the send APIs (0: disabled; 1: enabled).
send_callback = 1

# Whether to silence logging. (0: disabled; 1: enabled)
log_quiet = 0

# Log level. The options are LOG_DEBUG, LOG_VERBOSE, LOG_NOTICE, LOG_WARNING.
log_level = 3

# Log file path
log_file = "/var/log/iouring.log"

# Zero-copy memory to iouring
zero_copy = 1

# Whether to force the kernel sq background thread to be idle (0: disabled; 1: enabled).
sq_thread_force_idle = 1

# Interval at which the kernel sq background thread is woken up(unit: us)
sq_thread_wakeup_period = 100

# Whether the kernel sq background thread detaches from the service thread cpu/cpuset cgroup
sq_thread_detached = 0

# Initial iouring queue size
ring_size = 16384

# Maximum number of file descriptors
max_fd_num = 10240

# Number of rings created by one service thread
thread_ring_num = 1

# Number of global iouring_sqpoll threads in the process
sqpoll_num = 1

# Whether to enable fd thread occupation. Value 0: disabled; default value. Value 1: enabled. The thread exclusively occupies fd, and fd can be accessed without a lock, improving the sending and receiving performance.
fd_thread_exclusive = 1
